cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/circinus/circinus_op_overmos.fits	  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/circinus/circinus_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/ic1459/ic1459_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/ic1459/ic1459_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/ic2560/ic2560_op_overmos.fits	  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/ic2560/ic2560_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/ic4296/ic4296_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/ic4296/ic4296_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m104/m104_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m104/m104_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m105/m105_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m105/m105_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m106/m106_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m106/m106_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m31/m31_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m31/m31_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m32/m32_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m32/m32_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m49/m49_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m49/m49_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m59/m59_op_mos.fits			  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m59/m59_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m60/m60_op_mos.fits			  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m60/m60_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m64/m64_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m64/m64_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m77/m77_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m77/m77_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m81/m81_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m81/m81_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m84/m84_op_mos.fits			  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m84/m84_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m87/m87_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m87/m87_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m89/m89_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m89/m89_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m94/m94_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m94/m94_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/m96/m96_op_mos.fits			  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/m96/m96_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n0253/n0253_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n0253/n0253_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n0524/n0524_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n0524/n0524_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n0821/n0821_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n0821/n0821_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n1023/n1023_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n1023/n1023_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n1300/n1300_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n1300/n1300_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n1316/n1316_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n1316/n1316_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n1332/n1332_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n1332/n1332_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n1374/n1374_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n1374/n1374_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n2273/n2273_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n2273/n2273_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n2549/n2549_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n2549/n2549_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n2778/n2778_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n2778/n2778_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n2787/n2787_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n2787/n2787_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n2974/n2974_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n2974/n2974_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3079/n3079_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3079/n3079_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3091/n3091_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3091/n3091_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3115/n3115_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3115/n3115_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3227/n3227_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3227/n3227_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3245/n3245_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3245/n3245_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3377/n3377_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3377/n3377_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3384/n3384_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3384/n3384_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3393/n3393_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3393/n3393_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3414/n3414_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3414/n3414_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3489/n3489_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3489/n3489_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3585/n3585_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3585/n3585_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3607/n3607_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3607/n3607_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3608/n3608_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3608/n3608_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3842exp/n3842exp_op_overmos.fits	  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3842exp/n3842exp_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n3998/n3998_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n3998/n3998_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4026/n4026_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4026/n4026_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4151/n4151_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4151/n4151_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4261/n4261_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4261/n4261_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4291/n4291_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4291/n4291_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4342/n4342_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4342/n4342_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4388/n4388_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4388/n4388_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4459/n4459_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4459/n4459_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4473/n4473_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4473/n4473_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4486a/n4486a_op_overmos.fits	  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4486a/n4486a_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4564/n4564_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4564/n4564_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4596/n4596_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4596/n4596_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4697/n4697_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4697/n4697_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4889/n4889_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4889/n4889_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n4945/n4945_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n4945/n4945_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5077/n5077_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5077/n5077_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5128/n5128_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5128/n5128_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5576/n5576_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5576/n5576_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5813/n5813_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5813/n5813_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5845/n5845_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5845/n5845_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n5846/n5846_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n5846/n5846_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n6251/n6251_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n6251/n6251_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n7052/n7052_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n7052/n7052_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n7582/n7582_op_overmos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n7582/n7582_op_overmos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n7619/n7619_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n7619/n7619_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/n7768/n7768_op_mos.fits		  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/n7768/n7768_op_mos.fits
cp /Users/gsavorgnan/Dropbox/giulia_e_basta/SPITZER/galfit/ugc03789/ugc03789_op_mos.fits	  /Users/gsavorgnan/galaxy_vivisection/data/galaxies/ugc03789/ugc03789_op_mos.fits
