mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m105	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/circinus  
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/ic1459    
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/ic2560    
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/ic4296    
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m104	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m106	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m31	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m32	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m49	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m59	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m60	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m64	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m77	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m81	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m84	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m87	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m89	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m94	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/m96	   
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n0253     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n0524     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n0821     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1023     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1300     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1316     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1332     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1374     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n1399     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n2273     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n2549     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n2778     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n2787     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n2974     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3079     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3091     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3115     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3227     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3245     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3377     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3384     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3393     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3414     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3489     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3585     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3607     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3608     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3842exp  
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n3998     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4026     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4151     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4261     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4291     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4342     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4388     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4459     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4473     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4486a    
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4564     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4596     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4697     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4889     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n4945     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5077     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5128     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5576     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5813     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5845     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n5846     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n6251     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n7052     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n7582     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n7619     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/n7768     
mkdir /Users/gsavorgnan/galaxy_vivisection/analysis/galaxies/ugc03789  
